-- ═══════════════════════════════════════════════════════════════
-- AWE-OS v2 — Monetization Agent Schema
-- Run in Supabase SQL editor BEFORE deploying code changes.
-- All statements are idempotent (IF NOT EXISTS).
-- ═══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Monetization strategies generated by AI ──────────────────
CREATE TABLE IF NOT EXISTS monetization_strategies (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tool_id         UUID REFERENCES tools(id) ON DELETE CASCADE,
  tool_name       TEXT NOT NULL,

  strategy_type   TEXT NOT NULL CHECK (strategy_type IN (
                    'pricing', 'freemium', 'upsell', 'trial', 'bundle'
                  )),

  -- Snapshot of tool state at generation time
  current_revenue DECIMAL(10,2),
  current_model   TEXT,

  -- AI-generated recommendation object (structure varies by strategy_type)
  recommendation       JSONB NOT NULL,
  potential_impact     TEXT,
  confidence_score     INTEGER CHECK (confidence_score BETWEEN 0 AND 100),
  implementation_steps JSONB DEFAULT '[]',

  -- Human workflow
  status          TEXT NOT NULL DEFAULT 'suggested'
                  CHECK (status IN ('suggested', 'testing', 'implemented', 'rejected')),

  tested_at       TIMESTAMP,
  implemented_at  TIMESTAMP,
  result_notes    TEXT,
  created_at      TIMESTAMP DEFAULT NOW()
);

-- ── A/B pricing experiments ───────────────────────────────────
CREATE TABLE IF NOT EXISTS pricing_experiments (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tool_id         UUID REFERENCES tools(id) ON DELETE CASCADE,

  experiment_name   TEXT    NOT NULL,
  variant_a_price   DECIMAL(10,2) NOT NULL CHECK (variant_a_price > 0),
  variant_b_price   DECIMAL(10,2) NOT NULL CHECK (variant_b_price > 0),
  variant_a_label   TEXT    DEFAULT 'Control',
  variant_b_label   TEXT    DEFAULT 'Test',

  variant_a_conversions INTEGER DEFAULT 0,
  variant_b_conversions INTEGER DEFAULT 0,
  variant_a_views       INTEGER DEFAULT 0,
  variant_b_views       INTEGER DEFAULT 0,

  status          TEXT NOT NULL DEFAULT 'running'
                  CHECK (status IN ('running', 'completed', 'stopped')),

  winner          TEXT CHECK (winner IN ('A', 'B', 'tie')),
  started_at      TIMESTAMP DEFAULT NOW(),
  ended_at        TIMESTAMP,
  created_at      TIMESTAMP DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_mon_tool_id
  ON monetization_strategies(tool_id);

CREATE INDEX IF NOT EXISTS idx_mon_status
  ON monetization_strategies(status);

CREATE INDEX IF NOT EXISTS idx_mon_confidence
  ON monetization_strategies(confidence_score DESC);

CREATE INDEX IF NOT EXISTS idx_pricing_exp_tool_id
  ON pricing_experiments(tool_id);

CREATE INDEX IF NOT EXISTS idx_pricing_exp_status
  ON pricing_experiments(status);

-- ── Verify (run after migration) ──────────────────────────────
-- SELECT id, tool_name, strategy_type, confidence_score, status
-- FROM monetization_strategies LIMIT 5;
-- SELECT id, experiment_name, status, winner FROM pricing_experiments LIMIT 5;
