import { Helmet } from 'react-helmet-async'
import ContractWizard from '../../components/tools/contractgenerator/ContractWizard'

const SEO = {
  title: 'Contract Generator — Free Indian Freelance Contract Maker | AWE-OS',
  description:
    'Generate professional NDA, Service Agreement, and Employment contracts for Indian freelancers. Indian legal compliance check, GST/TDS advisories, and instant PDF download — free.',
  keywords:
    'contract generator india, freelance contract india, NDA generator india, service agreement india, employment contract india, GST contract, TDS freelance',
  canonical: 'https://www.awe-os.com/tools/contract-generator',
}

export default function ContractGenerator() {
  return (
    <>
      <Helmet>
        <title>{SEO.title}</title>
        <meta name="description" content={SEO.description} />
        <meta name="keywords" content={SEO.keywords} />
        <link rel="canonical" href={SEO.canonical} />
        <meta property="og:title" content={SEO.title} />
        <meta property="og:description" content={SEO.description} />
        <meta property="og:url" content={SEO.canonical} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={SEO.title} />
        <meta name="twitter:description" content={SEO.description} />
        <script type="application/ld+json">{JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'WebApplication',
          name: 'Contract Generator',
          description: SEO.description,
          url: SEO.canonical,
          applicationCategory: 'BusinessApplication',
          operatingSystem: 'Web',
          offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' },
        })}</script>
      </Helmet>

      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-slate-800 to-gray-900">
        {/* Top nav strip */}
        <div className="border-b border-white/10 bg-black/20 backdrop-blur-sm">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 py-3 flex items-center gap-2 text-xs text-gray-400">
            <a href="/" className="hover:text-white transition-colors">Home</a>
            <span>/</span>
            <a href="/tools" className="hover:text-white transition-colors">Tools</a>
            <span>/</span>
            <span className="text-gray-300">Contract Generator</span>
          </div>
        </div>

        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
          {/* Hero */}
          <div className="text-center mb-10">
            <div className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/30 rounded-full px-4 py-1.5 text-xs text-blue-300 font-medium mb-5">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse" />
              Indian Legal Compliance Built-In
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3 tracking-tight">
              Contract Generator
            </h1>
            <p className="text-gray-400 text-sm sm:text-base max-w-xl mx-auto leading-relaxed">
              Generate professional contracts for Indian freelancers in minutes.
              NDA, Service Agreement &amp; Employment Contract — with GST/TDS compliance checks and instant PDF export.
            </p>

            {/* Feature pills */}
            <div className="flex flex-wrap justify-center gap-2 mt-5">
              {[
                '🇮🇳 Indian Law',
                '📋 3 Contract Types',
                '✅ GST / TDS Check',
                '📥 PDF Export',
                '🔒 No Data Stored',
              ].map(f => (
                <span
                  key={f}
                  className="text-xs bg-white/5 border border-white/10 text-gray-300 px-3 py-1 rounded-full"
                >
                  {f}
                </span>
              ))}
            </div>
          </div>

          {/* Wizard */}
          <ContractWizard />

          {/* Disclaimer */}
          <div className="mt-8 bg-yellow-500/5 border border-yellow-500/20 rounded-2xl px-5 py-4">
            <p className="text-xs text-yellow-300/80 text-center leading-relaxed">
              <span className="font-semibold">Legal Disclaimer:</span> Contracts generated by this tool are templates
              for reference purposes only. They do not constitute legal advice. For legally binding agreements,
              consult a qualified legal professional familiar with Indian contract law.
            </p>
          </div>
        </div>
      </div>
    </>
  )
}
