import ContractWizard from '../../components/tools/contractgenerator/ContractWizard'
import ToolPageShell from './ToolPageShell'

// ── Contract wizard UI ────────────────────────────────────────────────────────

function ContractUI() {
  return (
    <div className="bg-gradient-to-br from-gray-900 via-slate-800 to-gray-900 rounded-2xl overflow-hidden">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12">

        {/* Feature pills */}
        <div className="flex flex-wrap justify-center gap-2 mb-8">
          {[
            '🇮🇳 Indian Law',
            '📋 3 Contract Types',
            '✅ GST / TDS Check',
            '📥 PDF Export',
            '🔒 No Data Stored',
          ].map(f => (
            <span
              key={f}
              className="text-xs bg-white/5 border border-white/10 text-gray-300 px-3 py-1 rounded-full"
            >
              {f}
            </span>
          ))}
        </div>

        {/* Wizard */}
        <ContractWizard />

        {/* Disclaimer */}
        <div className="mt-8 bg-yellow-500/5 border border-yellow-500/20 rounded-2xl px-5 py-4">
          <p className="text-xs text-yellow-300/80 text-center leading-relaxed">
            <span className="font-semibold">Legal Disclaimer:</span> Contracts generated by this tool are templates
            for reference purposes only. They do not constitute legal advice. For legally binding agreements,
            consult a qualified legal professional familiar with Indian contract law.
          </p>
        </div>
      </div>
    </div>
  )
}

// ── SEO content ───────────────────────────────────────────────────────────────

const STEPS = [
  'Choose your contract type: NDA for confidentiality protection before a project begins, Service Agreement for project-based freelance work, or Employment Contract for hiring employees or formalising a full-time role.',
  'Fill in Party A details — your name or company name, address, and GSTIN if you are GST-registered — then enter Party B details including your client or employer\'s information.',
  'Set the contract terms: scope of work, project duration, payment amount and schedule, and the Indian state whose laws will govern the agreement.',
  'Review the GST/TDS compliance advisory shown for your specific contract type. This flag tells you whether to include a GST line in the payment clause and whether a TDS deduction acknowledgment is needed.',
  'Click "Export PDF" to download your completed contract instantly. You can also copy the text into Word or Google Docs to make further edits before printing or sharing.',
]

const FAQS = [
  {
    q: 'Is the generated contract legally valid in India?',
    a: 'The contracts are structured in accordance with the Indian Contract Act, 1872 and include standard clauses recognised by Indian courts. A contract\'s legal validity depends on both parties signing, the presence of consideration, and clear intent — not on whether a tool or a lawyer drafted it. For complex engagements involving equity, IP ownership disputes, or amounts above ₹10 lakh, have a qualified advocate review the final agreement before signing.',
  },
  {
    q: 'What is the difference between an NDA, Service Agreement, and Employment Contract?',
    a: 'An NDA covers confidentiality only — it protects sensitive information shared before or during a business relationship, such as business ideas, pricing, or client lists. A Service Agreement covers the actual project: scope of work, deliverables, payment terms, IP ownership, and termination conditions. An Employment Contract covers a long-term employment relationship with provisions for salary, notice period, non-compete clauses, and post-employment restrictions. Use an NDA before sharing confidential information, a Service Agreement for project work, and an Employment Contract when hiring someone on a fixed salary.',
  },
  {
    q: 'Does this contract handle GST for Indian freelancers?',
    a: 'Yes. The tool generates GST-aware payment clauses and flags the applicable GST rate (18% for most services) in your contract. It notes whether GST registration is likely mandatory based on your revenue threshold — ₹20 lakh annually for most states, ₹10 lakh for special category states. Add your GSTIN to the contract if you\'re registered; the template notes when GST is not applicable for unregistered freelancers.',
  },
  {
    q: 'What is TDS and do I need to address it in my contract?',
    a: 'TDS (Tax Deducted at Source) is the mechanism by which payers withhold a portion of payment before disbursing it to the recipient. If your client is a registered company, they must typically deduct 10% TDS under Section 194J (professional services) before paying you. The contract template includes a TDS acknowledgment clause so both parties understand the gross payment vs. net disbursement from the start, avoiding payment disputes at invoice time.',
  },
  {
    q: 'Can I edit the generated contract after downloading it?',
    a: 'Yes. Download the PDF and extract the text, or copy the content directly from the tool into a Word or Google Docs document. You can then modify any clause — scope, payment schedule, jurisdiction, IP ownership — to match your specific situation. It\'s always advisable to adjust terms that don\'t perfectly reflect your agreement before asking the other party to sign.',
  },
  {
    q: 'Is my contract data stored on AWE-OS servers?',
    a: 'No. The entire contract is generated in your browser using JavaScript. None of the party details, project information, or payment terms you enter are transmitted to or stored on any server. When you close the browser tab, the data is gone. This makes the tool safe to use with sensitive client information, financial terms, and personal addresses.',
  },
]

const ABOUT = [
  'Your client just agreed to a ₹2 lakh project over WhatsApp. Now they want a formal contract before releasing the advance — and you\'re not sure what terms to include, whether you need a GST clause, or whether TDS applies to your payment. The AWE-OS Contract Generator fills that gap in three minutes: answer a few questions about the project, and download a professionally structured agreement tailored to Indian law.',
  'The tool generates three contract types used most commonly by Indian freelancers and small businesses. An NDA (Non-Disclosure Agreement) protects confidential information shared between parties — essential before pitching ideas, sharing proprietary processes, or beginning discovery calls with potential clients. A Service Agreement defines scope of work, payment terms, timelines, and intellectual property ownership for project-based engagements — the most common contract for freelance developers, designers, and consultants. An Employment Contract formalises full-time or part-time work arrangements with salary, notice period, non-compete clauses, and confidentiality obligations.',
  'Generic international contract templates miss the legal layers specific to India. Freelancers earning above ₹20 lakh annually must charge 18% GST on services; this must be addressed in your contract\'s payment clauses. Under Sections 194C and 194J of the Income Tax Act, clients that are registered companies must deduct 10% TDS before paying you — meaning your ₹1 lakh invoice results in a ₹90,000 payment with a TDS certificate for the rest. The Contract Generator flags these compliance points for your specific contract type and state, so you can build the right payment terms from the start and avoid disputes at billing time.',
  'All contracts are generated entirely in your browser — no data is sent to any server, and nothing is stored once you close the page. You can download the PDF, copy the text into Word or Google Docs for further editing, or share it directly via email or WhatsApp. These templates are professionally structured based on standard Indian legal practice and the Indian Contract Act, 1872. They are not a substitute for advice from a qualified advocate. For high-value agreements, equity arrangements, or anything involving disputed intellectual property, always have a legal professional review the contract before both parties sign.',
]

// ── Page export ───────────────────────────────────────────────────────────────

export default function ContractGenerator() {
  return (
    <ToolPageShell
      slug="contract-generator"
      name="Contract Generator"
      description="Generate professional NDA, Service Agreement, and Employment contracts for Indian freelancers with GST/TDS compliance checks and instant PDF export."
      icon="📝"
      steps={STEPS}
      faqs={FAQS}
      about={ABOUT}
      limitation={"Generates standard templates for common situations — have important contracts reviewed by a lawyer before signing."}
    >
      <ContractUI />
    </ToolPageShell>
  )
}
