-- ════════════════════════════════════════════════════════════════════════════════
-- AWE-OS Migration 015 — Marketplace Expansion Engine (Phase 6B)
--
-- New tables:
--   marketplace_opportunities        — ranked expansion opportunities
--   marketplace_expansion_history    — audit log of launches, rejections, trends
--   marketplace_health_snapshots     — periodic ecosystem health captures
--
-- Run against: Supabase service-role connection
-- Safe to re-run: all DDL uses IF NOT EXISTS
-- ════════════════════════════════════════════════════════════════════════════════


-- ── 1. Marketplace Opportunities ─────────────────────────────────────────────
-- Stores every detected expansion opportunity with ranking scores.
-- Generated by OpportunityRankingEngine; acted on by ToolLaunchCoordinator.
--
-- status values: pending | approved | rejected | in_progress | launched | expired

CREATE TABLE IF NOT EXISTS marketplace_opportunities (
  id                   UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  title                TEXT        NOT NULL,
  category             TEXT        NOT NULL,
  description          TEXT,
  seo_score            INTEGER     NOT NULL DEFAULT 0 CHECK (seo_score            BETWEEN 0 AND 100),
  monetization_score   INTEGER     NOT NULL DEFAULT 0 CHECK (monetization_score   BETWEEN 0 AND 100),
  opportunity_score    INTEGER     NOT NULL DEFAULT 0 CHECK (opportunity_score    BETWEEN 0 AND 100),
  saturation_risk      INTEGER     NOT NULL DEFAULT 0 CHECK (saturation_risk      BETWEEN 0 AND 100),
  implementation_score INTEGER     NOT NULL DEFAULT 0 CHECK (implementation_score BETWEEN 0 AND 100),
  roi_score            INTEGER     NOT NULL DEFAULT 0 CHECK (roi_score            BETWEEN 0 AND 100),
  launch_priority      INTEGER     NOT NULL DEFAULT 50 CHECK (launch_priority     BETWEEN 1 AND 100),
  trend_signal         TEXT        NOT NULL DEFAULT 'stable',
  generated_by         TEXT        NOT NULL DEFAULT 'expansion-engine',
  status               TEXT        NOT NULL DEFAULT 'pending',
  idea_id              UUID        REFERENCES generated_tool_ideas(id) ON DELETE SET NULL,
  factory_job_id       UUID,
  metadata             JSONB       NOT NULL DEFAULT '{}',
  expires_at           TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE marketplace_opportunities IS
  'Autonomous expansion opportunities ranked by priority. Feeds the launch queue.';

CREATE INDEX IF NOT EXISTS idx_mkt_opp_status_priority
  ON marketplace_opportunities (status, launch_priority DESC);

CREATE INDEX IF NOT EXISTS idx_mkt_opp_category_score
  ON marketplace_opportunities (category, opportunity_score DESC);

CREATE INDEX IF NOT EXISTS idx_mkt_opp_pending
  ON marketplace_opportunities (created_at DESC)
  WHERE status = 'pending';


-- ── 2. Marketplace Expansion History ─────────────────────────────────────────
-- Append-only event log of every expansion decision and outcome.
-- Powers MarketplaceLearningEngine pattern detection.
--
-- event_type values:
--   opportunity_detected  — new opportunity found by trend engine
--   opportunity_approved  — admin approved for launch
--   opportunity_rejected  — admin rejected
--   launch_queued         — added to build queue
--   launch_started        — factory run started
--   launch_completed      — tool published successfully
--   launch_failed         — factory run failed
--   category_paused       — expansion for category paused by admin
--   category_resumed      — expansion for category resumed
--   trend_spike           — unusual traffic/demand spike detected
--   trend_decline         — category traffic declining
--   saturation_warning    — category approaching saturation
--   rebalance_triggered   — ecosystem rebalance triggered

CREATE TABLE IF NOT EXISTS marketplace_expansion_history (
  id             UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  event_type     TEXT        NOT NULL,
  category       TEXT,
  opportunity_id UUID        REFERENCES marketplace_opportunities(id) ON DELETE SET NULL,
  tool_id        UUID,
  actor          TEXT        NOT NULL DEFAULT 'system',
  outcome        TEXT        NOT NULL DEFAULT 'pending',
  metadata       JSONB       NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE marketplace_expansion_history IS
  'Append-only expansion event log. Used by MarketplaceLearningEngine for adaptive strategy.';

CREATE INDEX IF NOT EXISTS idx_mkt_hist_event_time
  ON marketplace_expansion_history (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_mkt_hist_category_time
  ON marketplace_expansion_history (category, created_at DESC)
  WHERE category IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_mkt_hist_opportunity
  ON marketplace_expansion_history (opportunity_id)
  WHERE opportunity_id IS NOT NULL;


-- ── 3. Marketplace Health Snapshots ──────────────────────────────────────────
-- Periodic point-in-time captures of ecosystem health metrics.
-- Taken on-demand and cached; used for trend charting.

CREATE TABLE IF NOT EXISTS marketplace_health_snapshots (
  id                    UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  ecosystem_score       INTEGER     NOT NULL DEFAULT 0 CHECK (ecosystem_score BETWEEN 0 AND 100),
  category_distribution JSONB       NOT NULL DEFAULT '{}',
  revenue_balance_score INTEGER     NOT NULL DEFAULT 0,
  traffic_diversity_score INTEGER   NOT NULL DEFAULT 0,
  quality_trend_score   INTEGER     NOT NULL DEFAULT 0,
  tool_count            INTEGER     NOT NULL DEFAULT 0,
  active_tool_count     INTEGER     NOT NULL DEFAULT 0,
  inactive_tool_count   INTEGER     NOT NULL DEFAULT 0,
  risk_flags            JSONB       NOT NULL DEFAULT '[]',
  recommendations       JSONB       NOT NULL DEFAULT '[]',
  snapshot_metadata     JSONB       NOT NULL DEFAULT '{}',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE marketplace_health_snapshots IS
  'Periodic ecosystem health captures for trend analysis and rebalancing decisions.';

CREATE INDEX IF NOT EXISTS idx_mkt_health_created
  ON marketplace_health_snapshots (created_at DESC);


-- ── Trigger: keep updated_at current on marketplace_opportunities ─────────────

CREATE OR REPLACE FUNCTION update_marketplace_opportunities_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_marketplace_opportunities_updated_at ON marketplace_opportunities;
CREATE TRIGGER trg_marketplace_opportunities_updated_at
  BEFORE UPDATE ON marketplace_opportunities
  FOR EACH ROW EXECUTE FUNCTION update_marketplace_opportunities_updated_at();
