import { Helmet } from 'react-helmet-async'
import { Link } from 'react-router-dom'

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-600 text-sm leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

export default function Disclaimer() {
  return (
    <>
      <Helmet>
        <title>Disclaimer — AWE-OS</title>
        <meta name="description" content="AWE-OS Disclaimer — important information about tool accuracy, limitations, and the absence of professional financial, medical, or legal advice." />
        <link rel="canonical" href="https://awe-os.com/disclaimer" />
      </Helmet>

      {/* Hero */}
      <section className="bg-gradient-to-b from-blue-50 to-white py-14 px-4 text-center">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3">Disclaimer</h1>
          <p className="text-gray-500 text-base">
            Please read this disclaimer carefully before using the tools and services provided by AWE-OS at awe-os.com.
          </p>
          <p className="text-sm text-gray-400 mt-3">Last updated: May 8, 2026</p>
        </div>
      </section>

      <div className="max-w-3xl mx-auto px-4 py-14">

        <Section title="1. General Disclaimer">
          <p>
            The information, tools, calculators, converters and AI-generated content available on AWE-OS (awe-os.com) are provided
            strictly for general informational and educational purposes. While we make every reasonable effort to ensure
            the accuracy and reliability of our tools, AWE-OS makes no representations or warranties of any kind —
            express, implied, statutory or otherwise — about the completeness, accuracy, reliability, suitability or
            availability of any tool, result or content on this platform.
          </p>
          <p>
            Any reliance you place on information or results generated by our tools is strictly at your own risk.
            AWE-OS expressly disclaims all liability for any errors, omissions, or inaccuracies in tool outputs,
            and for any loss or damage — direct or indirect — arising from your use of or reliance on any content
            or tool on this platform.
          </p>
        </Section>

        <Section title="2. No Financial Advice">
          <p>
            AWE-OS offers financial calculation tools such as loan calculators, EMI calculators, compound interest
            calculators, percentage calculators, and similar utilities. These tools are designed to help you
            perform mathematical computations quickly and conveniently.
          </p>
          <p>
            <strong>Nothing on AWE-OS constitutes financial advice.</strong> The results produced by our financial
            calculators are estimates based on the inputs you provide and standard mathematical formulas. They are
            not a substitute for advice from a qualified financial advisor, accountant, or investment professional.
          </p>
          <p>
            Financial decisions — including but not limited to loans, investments, tax planning, budgeting and
            retirement planning — involve complex variables, regulatory requirements and personal circumstances
            that our tools cannot fully account for. Before making any financial decision, consult a licensed
            financial professional who can assess your specific situation.
          </p>
          <p>
            AWE-OS is not a registered financial advisor, broker, or investment service. We do not provide
            personalised financial planning, investment recommendations, or tax advice. All financial tool
            outputs should be treated as rough estimates only.
          </p>
        </Section>

        <Section title="3. No Medical or Health Advice">
          <p>
            AWE-OS offers health-related tools such as BMI calculators, calorie estimators, age calculators and
            similar health metrics tools. These tools are provided for general informational purposes only.
          </p>
          <p>
            <strong>Nothing on AWE-OS constitutes medical advice, diagnosis, or treatment.</strong> The results
            from our health and wellness calculators are based on general population formulas (such as WHO and
            CDC guidelines) and do not account for individual medical history, pre-existing conditions,
            medications, or other personal health factors.
          </p>
          <p>
            BMI, for example, is a general population screening tool with well-documented limitations — it does
            not distinguish between muscle mass and fat, and it may not accurately reflect health risk for all
            individuals. Similarly, calorie and nutritional calculators provide estimates only.
          </p>
          <p>
            Always consult a qualified healthcare professional, physician or registered dietitian before making
            decisions about your health, diet, exercise or medical treatment. AWE-OS is not responsible for
            any health decisions made based on the outputs of our tools.
          </p>
        </Section>

        <Section title="4. No Legal Advice">
          <p>
            Some tools on AWE-OS — such as document converters, invoice generators, contract templates and
            content generators — may produce documents, text, or other outputs that have legal implications.
          </p>
          <p>
            <strong>Nothing on AWE-OS constitutes legal advice.</strong> The documents, templates, and
            text generated by our tools are provided for general informational purposes only and should not
            be treated as legal counsel or used as a substitute for the advice of a qualified attorney.
          </p>
          <p>
            Laws vary significantly by jurisdiction, and no automated tool can account for the full complexity
            of your legal situation. Documents generated by AWE-OS tools — including invoices, contracts,
            resumes, and letters — should be reviewed by a licensed legal professional before being used
            in formal or legally binding contexts.
          </p>
          <p>
            AWE-OS is not a law firm, and no attorney-client relationship is created by your use of this platform.
          </p>
        </Section>

        <Section title="5. AI-Generated Content Disclaimer">
          <p>
            Several tools on AWE-OS use artificial intelligence — including large language models (LLMs) —
            to generate text, summaries, rewritten content, resumes, cover letters and other outputs.
          </p>
          <p>
            AI-generated content is produced by statistical models and may contain errors, inaccuracies,
            outdated information, or content that does not fully meet your needs. AI outputs should
            always be reviewed, fact-checked and edited by a qualified human before being used in any
            professional, academic, medical, legal or financial context.
          </p>
          <p>
            AWE-OS does not guarantee that AI-generated content is original, free from plagiarism, or
            suitable for any particular purpose. You are responsible for verifying the appropriateness
            and accuracy of AI outputs before acting on them.
          </p>
        </Section>

        <Section title="6. Tool Accuracy and Limitations">
          <p>
            AWE-OS tools are built using widely accepted algorithms, mathematical formulas, and industry-standard
            methods. However, all digital tools have inherent limitations:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Results are only as accurate as the inputs you provide</li>
            <li>Rounding, floating-point arithmetic, and approximation methods may introduce minor inaccuracies</li>
            <li>Unit converters use standardised conversion factors which may not account for regional variations</li>
            <li>PDF tools may not preserve all formatting from every document type or version</li>
            <li>Image compression tools balance quality and file size — results vary by image content</li>
            <li>AI writing tools reflect training data up to a knowledge cut-off date and may lack current information</li>
          </ul>
          <p>
            We continuously improve our tools, but we make no guarantee that they will be error-free, meet
            your requirements, or produce results suitable for any specific application.
          </p>
        </Section>

        <Section title="7. External Links">
          <p>
            AWE-OS may contain links to external websites and services that are not operated by us. These
            links are provided for your convenience only. We have no control over the content, accuracy,
            or availability of external sites and accept no responsibility or liability for them.
          </p>
          <p>
            The inclusion of a link does not imply our endorsement, recommendation, or approval of the
            linked website or its content. Visit external links at your own discretion.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            To the fullest extent permitted by applicable law, AWE-OS, its founders, employees, agents,
            partners and affiliates shall not be liable for any direct, indirect, incidental, consequential,
            special or punitive damages — including but not limited to loss of income, data, business,
            health, legal standing, or goodwill — arising from:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Your use of or inability to use any tool, feature, or content on AWE-OS</li>
            <li>Errors, omissions, or inaccuracies in tool outputs</li>
            <li>Decisions made based on information or results from our tools</li>
            <li>Temporary or permanent unavailability of the platform</li>
            <li>Unauthorised access to or alteration of your data</li>
          </ul>
          <p>
            This limitation applies regardless of whether AWE-OS was advised of the possibility of such damages.
          </p>
        </Section>

        <Section title="9. Amendments to This Disclaimer">
          <p>
            AWE-OS reserves the right to modify, update, or replace this Disclaimer at any time without
            prior notice. Changes take effect immediately upon being posted to this page. The &quot;Last updated&quot;
            date at the top of this page indicates when the Disclaimer was most recently revised.
          </p>
          <p>
            Your continued use of AWE-OS following the posting of changes to this Disclaimer constitutes
            your acceptance of those changes. We encourage you to review this page periodically.
          </p>
        </Section>

        <Section title="10. Contact Us">
          <p>
            If you have questions about this Disclaimer or concerns about the accuracy of any tool result,
            we want to hear from you. Reach us at:
          </p>
          <p>
            <strong>Email:</strong>{' '}
            <a href="mailto:wajid081986@gmail.com" className="text-blue-600 hover:underline">
              wajid081986@gmail.com
            </a>
          </p>
          <p>
            <strong>Contact form:</strong>{' '}
            <Link to="/contact" className="text-blue-600 hover:underline">
              awe-os.com/contact
            </Link>
          </p>
        </Section>

      </div>
    </>
  )
}
