import { Helmet } from 'react-helmet-async'

function Section({ title, children }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-600 text-sm leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms of Service — AWE-OS</title>
        <meta name="description"         content="AWE-OS Terms of Service. Free to use for personal and commercial purposes. No sign-up required. Read our terms before using the platform." />
        <link rel="canonical"            href="https://www.awe-os.com/terms" />
        <meta property="og:site_name"    content="AWE-OS" />
        <meta property="og:locale"       content="en_US" />
        <meta property="og:title"        content="Terms of Service — AWE-OS" />
        <meta property="og:description"  content="AWE-OS Terms of Service. Free to use for personal and commercial purposes. No sign-up required." />
        <meta property="og:url"          content="https://www.awe-os.com/terms" />
        <meta property="og:type"         content="website" />
        <meta property="og:image"        content="https://www.awe-os.com/og-image.svg" />
        <meta property="og:image:width"  content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt"    content="AWE-OS Terms of Service" />
        <meta name="twitter:card"        content="summary_large_image" />
        <meta name="twitter:site"        content="@awe_os" />
        <meta name="twitter:title"       content="Terms of Service — AWE-OS" />
        <meta name="twitter:description" content="AWE-OS Terms of Service. Free to use for personal and commercial purposes. No sign-up required." />
        <meta name="twitter:image"       content="https://www.awe-os.com/og-image.svg" />
        <meta name="twitter:image:alt"   content="AWE-OS Terms of Service" />
      </Helmet>

      <div className="max-w-3xl mx-auto px-4 py-14">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-gray-900 mb-3">Terms of Service</h1>
          <p className="text-sm text-gray-400">Last updated: June 1, 2026</p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using AWE-OS (&quot;Service&quot;, &quot;Platform&quot;, &quot;we&quot;,
            &quot;us&quot;) at awe-os.com, you agree to be bound by these Terms of Service. If you do
            not agree with any part of these terms, you must not use AWE-OS.
          </p>
          <p>
            We reserve the right to update these Terms at any time. Changes take effect immediately
            upon posting. Continued use of AWE-OS after a change constitutes your acceptance of the
            revised Terms. The &quot;Last updated&quot; date at the top of this page always reflects
            when the Terms were most recently changed.
          </p>
        </Section>

        <Section title="2. Free Use — Personal and Commercial">
          <p>
            AWE-OS tools are <strong>free to use for both personal and commercial purposes</strong>.
            No sign-up, subscription, or payment is required to access any tool on the platform.
          </p>
          <p>You are permitted to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use all tools on AWE-OS for personal projects, freelance work, and business use</li>
            <li>Use outputs generated by AWE-OS tools in commercial products and client deliverables</li>
            <li>Share links to AWE-OS tools freely</li>
          </ul>
          <p>You must not:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any unlawful purpose or in violation of applicable law</li>
            <li>Attempt to reverse-engineer, scrape, or systematically copy AWE-OS content or tools</li>
            <li>Use automated bots or scripts to access the Service at rates exceeding normal human use</li>
            <li>Infringe the intellectual property rights of AWE-OS or any third party</li>
            <li>Submit malicious code, viruses, or any content designed to disrupt the platform</li>
          </ul>
        </Section>

        <Section title="3. No Warranty">
          <p>
            AWE-OS is provided <strong>&quot;as is&quot;</strong> and{' '}
            <strong>&quot;as available&quot;</strong> without warranties of any kind, either express
            or implied. We make no warranty that:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>The Service will be uninterrupted, error-free, or always available</li>
            <li>Tool outputs will be accurate, complete, or fit for any particular purpose</li>
            <li>Any defects or errors will be corrected</li>
          </ul>
          <p>
            You use AWE-OS at your own risk. We disclaim all implied warranties, including
            merchantability, fitness for a particular purpose, and non-infringement to the fullest
            extent permitted by law.
          </p>
        </Section>

        <Section title="4. Limitation of Liability">
          <p>
            To the maximum extent permitted by applicable law, AWE-OS and its owners shall not be
            liable for any indirect, incidental, special, consequential, or punitive damages arising
            from your use of — or inability to use — the Service.
          </p>
          <p>This includes, without limitation:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Loss of data or files</li>
            <li>Loss of profits or business revenue</li>
            <li>Decisions made based on tool outputs</li>
            <li>Service interruptions or downtime</li>
          </ul>
          <p>
            Because AWE-OS is a free service, our total liability to you for any claim, regardless
            of its basis, shall not exceed INR 100 (Indian Rupees one hundred).
          </p>
        </Section>

        <Section title="5. Intellectual Property">
          <p>
            All original content on AWE-OS — including the platform design, tool interfaces,
            branding, and written content — is the intellectual property of AWE-OS and is protected
            under applicable copyright law.
          </p>
          <p>
            <strong>Your inputs and outputs belong to you.</strong> Files you upload, text you enter,
            and results generated by our tools remain your property. By using AWE-OS, you grant us
            no licence to your content — it stays on your device and we never see it.
          </p>
          <p>
            You may not reproduce, republish, or create derivative works from AWE-OS&apos;s own
            content (tool UI, branding, marketing copy) without prior written permission.
          </p>
        </Section>

        <Section title="6. Governing Law">
          <p>
            These Terms of Service are governed by and construed in accordance with the laws of
            India, including the Information Technology Act 2000 and applicable rules thereunder.
          </p>
          <p>
            Any disputes arising out of or relating to these Terms or your use of AWE-OS shall be
            subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, India.
          </p>
          <p>
            If you have questions about these Terms, please contact us at{' '}
            <a href="mailto:contact@awe-os.com" className="text-blue-600 hover:underline">
              contact@awe-os.com
            </a>{' '}
            or via the{' '}
            <a href="/contact" className="text-blue-600 hover:underline">
              contact form
            </a>
            .
          </p>
        </Section>
      </div>
    </>
  )
}
