const express    = require('express');
const PDFDocument = require('pdfkit');
const corporate  = require('../templates/corporate');
const creative   = require('../templates/creative');
const minimal    = require('../templates/minimal');

const router = express.Router();

// Templates available to each tier
const FREE_TEMPLATE    = 'corporate';
const PREMIUM_TEMPLATES = new Set(['creative', 'minimal']);
const ALL_TEMPLATES    = { corporate, creative, minimal };

// ── Watermark ────────────────────────────────────────────
function addWatermark(doc) {
  const PW = doc.page.width;
  const PH = doc.page.height;

  // Diagonal stamp across the full page
  doc.save();
  doc.translate(PW / 2, PH / 2);
  doc.rotate(-45);
  doc.font('Helvetica-Bold').fontSize(56).fillColor('#D1D5DB')
     .text('Generated by AWE-OS', -190, -28, { lineBreak: false, characterSpacing: 1 });
  doc.restore();

  // Footer notice
  doc.font('Helvetica').fontSize(8).fillColor('#9CA3AF')
     .text(
       'Generated with AWE-OS Resume Builder (Free Plan) · Upgrade to remove watermark',
       0, PH - 22, { width: PW, align: 'center', lineBreak: false }
     );
}

// ── Route ────────────────────────────────────────────────
router.post('/generate-resume', (req, res) => {
  const { name, template = FREE_TEMPLATE, isPremium = false, ...rest } = req.body;

  if (!name || !name.trim()) {
    return res.status(400).json({ error: 'Name is required' });
  }

  // Enforce tier server-side — client flag cannot be trusted in production;
  // replace `isPremium` here with a real JWT/session check when adding auth.
  const resolvedTemplate =
    isPremium || !PREMIUM_TEMPLATES.has(template) ? template : FREE_TEMPLATE;

  const generate = ALL_TEMPLATES[resolvedTemplate] || ALL_TEMPLATES[FREE_TEMPLATE];
  const applyWatermark = !isPremium;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${name.trim().replace(/\s+/g, '_')}_Resume.pdf"`
  );

  try {
    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    doc.pipe(res);

    generate(doc, { name: name.trim(), ...rest });

    if (applyWatermark) addWatermark(doc);

    doc.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF' });
    }
  }
});

module.exports = router;
