const express     = require('express');
const PDFDocument = require('pdfkit');
const corporate   = require('../templates/corporate');
const creative    = require('../templates/creative');
const minimal     = require('../templates/minimal');

// ===== NEW CODE START =====
const Razorpay    = require('razorpay');
const crypto      = require('crypto');
const jwt         = require('jsonwebtoken');
const { z }       = require('zod');
const supabase    = require('../db/supabase');
const requireAuth = require('../middleware/auth');

const razorpay = new Razorpay({
  key_id:     process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET,
});

const EXPECTED_AMOUNT = Number(process.env.PREMIUM_PRICE || 4900);   // paise — ₹49
const EXPECTED_CURRENCY = 'INR';
// ===== NEW CODE END =====

const router = express.Router();

const FREE_TEMPLATE      = 'corporate';
const PREMIUM_TEMPLATES  = new Set(['creative', 'minimal']);
const ALL_TEMPLATES      = { corporate, creative, minimal };

// ── Watermark ─────────────────────────────────────────────────
function addWatermark(doc) {
  const PW = doc.page.width;
  const PH = doc.page.height;

  doc.save();
  doc.translate(PW / 2, PH / 2);
  doc.rotate(-45);
  doc.font('Helvetica-Bold').fontSize(56).fillColor('#D1D5DB')
     .text('Generated by AWE-OS', -190, -28, { lineBreak: false, characterSpacing: 1 });
     
  doc.restore();

  doc.font('Helvetica').fontSize(8).fillColor('#9CA3AF')
     .text(
       'Generated with AWE-OS Resume Builder (Free Plan) · Upgrade to remove watermark',
       0, PH - 22, { width: PW, align: 'center', lineBreak: false }
     );
}

// ── POST /api/generate-resume ──────────────────────────────────
router.post('/generate-resume', async (req, res) => {
  const { name, template = FREE_TEMPLATE, ...rest } = req.body;

  if (!name || !name.trim()) {
    return res.status(400).json({ error: 'Name is required' });
  }

  // ===== NEW CODE START =====
  // Check DB for premium status — never trust client-sent flag
  let isDbPremium = false;
  const authHeader = req.headers.authorization;
  if (authHeader?.startsWith('Bearer ')) {
    try {
      const payload = jwt.verify(authHeader.slice(7), process.env.JWT_SECRET);
      const { data } = await supabase
        .from('users')
        .select('is_premium')
        .eq('id', payload.userId)
        .maybeSingle();
      isDbPremium = data?.is_premium || false;
    } catch (_) {
      // Invalid/expired token — treat as free user
    }
  }

  const resolvedTemplate =
    isDbPremium && ALL_TEMPLATES[template] ? template : FREE_TEMPLATE;
  const applyWatermark = !isDbPremium;
  // ===== NEW CODE END =====

  const generate = ALL_TEMPLATES[resolvedTemplate] || ALL_TEMPLATES[FREE_TEMPLATE];

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="${name.trim().replace(/\s+/g, '_')}_Resume.pdf"`
  );

  try {
    const doc = new PDFDocument({ margin: 0, size: 'A4' });
    doc.pipe(res);

    generate(doc, { name: name.trim(), ...rest });

    if (applyWatermark) addWatermark(doc);

    doc.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF' });
    }
  }
});

// ===== NEW CODE START =====

// ── POST /api/create-order ─────────────────────────────────────
router.post('/create-order', requireAuth, async (req, res) => {
  try {
    const order = await razorpay.orders.create({
      amount:   EXPECTED_AMOUNT,
      currency: EXPECTED_CURRENCY,
      receipt:  `receipt_${Date.now()}`,
    });

    return res.json({ success: true, order });
  } catch (err) {
    console.error('Razorpay create-order error:', err.message);
    return res.status(500).json({ success: false, error: 'Failed to create order' });
  }
});

// ── Zod schema for verify-payment ─────────────────────────────
const VerifySchema = z.object({
  razorpay_order_id:   z.string().min(1),
  razorpay_payment_id: z.string().min(1),
  razorpay_signature:  z.string().min(1),
});

// ── POST /api/verify-payment ───────────────────────────────────
router.post('/verify-payment', requireAuth, async (req, res) => {
  const parsed = VerifySchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ success: false, error: 'Invalid payment data' });
  }

  const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = parsed.data;

  try {
    // 1. Verify HMAC signature
    const expectedSignature = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(`${razorpay_order_id}|${razorpay_payment_id}`)
      .digest('hex');

    if (expectedSignature !== razorpay_signature) {
      return res.status(400).json({ success: false, error: 'Signature mismatch' });
    }

    // 2. Verify order amount and currency with Razorpay API
    const order = await razorpay.orders.fetch(razorpay_order_id);
    if (!order || order.amount !== EXPECTED_AMOUNT || order.currency !== EXPECTED_CURRENCY) {
      return res.status(400).json({ success: false, error: 'Order amount mismatch' });
    }

    // 3. Prevent duplicate premium updates
    const { data: user, error: fetchErr } = await supabase
      .from('users')
      .select('is_premium, razorpay_payment_id')
      .eq('id', req.user.userId)
      .single();

    if (fetchErr) throw fetchErr;

    if (user?.is_premium) {
      return res.json({ success: true, message: 'Already premium' });
    }

    // 4. Update DB — never overwrite existing razorpay_payment_id
    const updateData = { is_premium: true };
    if (!user?.razorpay_payment_id) {
      updateData.razorpay_payment_id = razorpay_payment_id;
      updateData.razorpay_order_id   = razorpay_order_id;
    }

    const { error: updateErr } = await supabase
      .from('users')
      .update(updateData)
      .eq('id', req.user.userId);

    if (updateErr) throw updateErr;

    return res.json({ success: true, message: 'Payment verified' });
  } catch (err) {
    console.error('Verify payment error:', err.message);
    return res.status(500).json({ success: false, error: 'Verification failed' });
  }
});
// ===== NEW CODE END =====

module.exports = router;
