import { useState, useRef } from 'react'
import * as pdfjsLib from 'pdfjs-dist'
import pdfjsWorkerSrc from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import ToolPageShell from '../ToolPageShell'

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorkerSrc

const STEPS = [
  "Upload a PDF file by clicking the upload area or dragging and dropping a file onto it. The tool accepts standard PDF files up to 50 MB. Files that consist entirely of scanned images — pages photographed or photocopied into a PDF without optical character recognition applied — will produce empty or near-empty text output. Text extraction only works on PDFs that have embedded text, which includes most digitally created documents such as Word exports, government e-documents, financial statements, and typeset publications.",
  "After upload, text extraction begins automatically. The tool processes each page in sequence using the PDF.js library, extracting all text content while preserving relative reading order. Progress is shown by page as each one completes. For a standard 10-page text document, extraction typically takes 3–8 seconds depending on page complexity and the number of text elements on each page.",
  "The extracted text appears in the output panel. Each page is separated by a divider showing the page number, making it easy to locate content from a specific page. The text preserves the reading sequence of words as they appear in the PDF's internal content stream — column layouts and complex table structures may not extract perfectly, as multi-column arrangements often interleave text from adjacent columns rather than maintaining column-by-column reading order.",
  "Review the extracted text and make corrections as needed. The output textarea is fully editable — you can remove extraction artefacts like page header repetitions, fix column interleaving issues, or delete content from specific pages before copying. Click 'Copy All' to place the complete text on your clipboard for pasting into a document editor, search tool, translation service, or text processor.",
  "Click 'Download .txt' to save the extracted text as a plain text file named with the original PDF filename. The text file uses UTF-8 encoding and preserves line breaks from the extraction. If you need the text in a specific encoding or need to remove non-printable characters that occasionally appear in PDF text extractions, open the downloaded file in a text editor and use find-and-replace to clean up any anomalies.",
]

const FAQS = [
  {
    q: 'Why does my PDF produce empty text after extraction?',
    a: "Empty extraction almost always means the PDF contains scanned images rather than embedded text. A scanned PDF is a photograph of a document — the page content is stored as a raster image and the PDF has no text layer that can be read programmatically. Common examples include scanned government certificates, photocopied agreements, old bank statements scanned to PDF, and photographs saved as PDF. To extract text from scanned PDFs, you need OCR (Optical Character Recognition) software such as Adobe Acrobat Pro, Google Docs (upload the PDF and it runs OCR automatically), or Tesseract OCR. This tool cannot perform OCR — it reads only the text that is already embedded in the PDF's content stream.",
  },
  {
    q: 'Why is the extracted text in the wrong order or columns mixed up?',
    a: "PDF does not inherently store text in linear reading order — it stores text elements at absolute positions on a page. PDF.js attempts to reconstruct reading order by sorting text elements by vertical and horizontal position, but multi-column layouts, tables, and text boxes placed out of order can produce unexpected sequences in the extracted output. A two-column academic paper, for example, may extract text that alternates between the left and right columns sentence by sentence. This is a fundamental limitation of text extraction from PDFs not created with accessibility tagging. Post-extraction editing in the textarea or a text editor is usually the most practical fix for column interleaving issues.",
  },
  {
    q: 'What types of PDFs give the best extraction results?',
    a: "PDFs that extract most cleanly are those created digitally from a word processor, typesetting system, or structured data export: Microsoft Word/Google Docs exports, financial reports generated by accounting software, e-government documents like ITR acknowledgements and PAN card PDFs, court e-filings, academic papers downloaded from publisher websites, and e-books from legitimate sources. These have properly embedded text with Unicode character encoding. PDFs with best-effort extraction (readable but with some artefacts) include typeset books and complex formatted reports. PDFs that extract poorly or not at all: scanned images, PDFs generated from bitmap-only sources, and older PDFs using non-standard font encodings.",
  },
  {
    q: 'Can this tool extract text from password-protected PDFs?',
    a: "No. Password-protected PDFs that require a password to open cannot be processed — they are encrypted and their contents, including the text layer, are not accessible without decrypting the file first. If you have the owner password or user password, use the AWE-OS Unlock PDF tool to remove the restriction before attempting text extraction. PDFs that have editing restrictions (owner-level restrictions) but can be opened and viewed without a password can generally be text-extracted, as the restriction only applies to modification and printing — the text layer is accessible for reading and therefore for extraction.",
  },
  {
    q: 'Does extracting text from a PDF violate copyright?',
    a: "Text extraction for personal use — reading, study, research, translation, or accessibility purposes — generally falls within fair use provisions in India under Section 52 of the Copyright Act, 1957. Reproducing extracted text for publication, commercial use, or distribution without the copyright holder's permission may constitute infringement. For academic papers, extraction for personal study notes is standard practice. For commercially published books, e-books, or reports, check the publisher's terms of use. For government documents and official publications in India, most content is in the public domain or available under open government licensing, making extraction and reuse straightforward.",
  },
  {
    q: 'Is my PDF uploaded to any server during extraction?',
    a: "No — the PDF never leaves your device. The file is read into browser memory using the FileReader API, and all text extraction runs locally using the PDF.js library which executes in your browser's JavaScript engine. No file data is transmitted to any server at any point during the extraction process. The extracted text is rendered directly in the browser's DOM and copied or downloaded from local memory. This makes the tool safe for processing confidential documents: salary slips, income tax returns, bank statements, legal agreements, medical records, or any document you would not want uploaded to a third-party service.",
  },
]

const ABOUT = [
  'The PDF to Text tool extracts all embedded text from a PDF file and presents it as editable plain text, ready to copy or download. Upload a PDF and the tool processes each page in sequence, pulling out the text content from the document\'s internal structure without requiring any server-side processing. The extracted text is displayed with page separators so you can locate content from a specific section quickly.',
  'Text extraction from PDFs is useful across a wide range of tasks: searching a document that opens in a viewer without a search function, copying text from a PDF that disables selection and copy, preparing content for translation or accessibility tools, extracting data from financial reports or official government documents, feeding PDF content into AI tools that accept only plain text, and archiving document content in a portable, searchable format.',
  'The tool extracts text in the order it is stored in the PDF\'s content stream, which closely follows the visual reading order for simple documents. Complex layouts — multi-column text, text boxes placed out of sequence, mixed-direction scripts, or tables — may require some manual rearrangement of the extracted output. The output textarea is editable, making it straightforward to clean up artefacts or reorder content as needed before copying or downloading.',
  'All extraction runs locally in your browser using PDF.js, a trusted open-source PDF rendering library maintained by Mozilla. No file data is sent to any server, and the tool works offline once the page has loaded. The tool processes text-based PDFs only — scanned image PDFs require OCR software to convert the image content to searchable text before extraction is possible.',
]

function PDFtoTextTool() {
  const [pages, setPages]   = useState([])
  const [status, setStatus] = useState('idle')
  const [progress, setProgress] = useState({ done: 0, total: 0 })
  const [copied, setCopied] = useState(false)
  const [filename, setFilename] = useState('extracted')
  const fileRef = useRef()

  const process = async (file) => {
    if (!file || !file.name.toLowerCase().endsWith('.pdf')) return
    setFilename(file.name.replace(/\.pdf$/i, ''))
    setPages([]); setStatus('extracting'); setProgress({ done: 0, total: 0 })

    try {
      const buf = await file.arrayBuffer()
      const pdf = await pdfjsLib.getDocument({ data: buf }).promise
      setProgress({ done: 0, total: pdf.numPages })
      const extracted = []

      for (let i = 1; i <= pdf.numPages; i++) {
        const page    = await pdf.getPage(i)
        const content = await page.getTextContent()
        const text    = content.items.map(item => item.str).join(' ').trim()
        extracted.push({ page: i, text })
        setProgress({ done: i, total: pdf.numPages })
      }

      setPages(extracted)
      setStatus('done')
    } catch {
      setStatus('error')
    }
  }

  const allText = pages.map(p => `--- Page ${p.page} ---\n${p.text}`).join('\n\n')

  const copy = async () => {
    await navigator.clipboard.writeText(allText)
    setCopied(true); setTimeout(() => setCopied(false), 2000)
  }

  const download = () => {
    const blob = new Blob([allText], { type: 'text/plain;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = `${filename}.txt`; a.click()
    URL.revokeObjectURL(url)
  }

  const wordCount = allText.trim() ? allText.trim().split(/\s+/).length : 0

  return (
    <div className="space-y-4">
      {/* Upload */}
      <div
        onDragOver={e => e.preventDefault()}
        onDrop={e => { e.preventDefault(); process(e.dataTransfer.files[0]) }}
        onClick={() => fileRef.current?.click()}
        className="border-2 border-dashed border-gray-200 rounded-xl p-8 text-center cursor-pointer hover:border-blue-400 hover:bg-blue-50/20 transition-colors"
      >
        <p className="text-2xl mb-2">📄</p>
        <p className="text-gray-500 text-sm">Drop a PDF or <span className="text-blue-600 font-medium">click to browse</span></p>
        <p className="text-xs text-gray-400 mt-1">Text-based PDFs only · up to 50 MB</p>
        <input ref={fileRef} type="file" accept=".pdf" className="hidden"
          onChange={e => process(e.target.files[0])} />
      </div>

      {/* Progress */}
      {status === 'extracting' && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
          <p className="text-sm text-blue-700 font-medium mb-2">
            Extracting text… page {progress.done} of {progress.total}
          </p>
          <div className="h-2 bg-blue-100 rounded-full overflow-hidden">
            <div className="h-full bg-blue-500 rounded-full transition-all"
              style={{ width: progress.total ? `${(progress.done / progress.total) * 100}%` : '0%' }} />
          </div>
        </div>
      )}

      {status === 'error' && (
        <p className="text-red-500 text-sm text-center">Could not extract text. Make sure the file is a valid, non-encrypted PDF.</p>
      )}

      {/* Output */}
      {status === 'done' && pages.length > 0 && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-500">{pages.length} page{pages.length !== 1 ? 's' : ''} · {wordCount.toLocaleString()} words</p>
            <div className="flex gap-2">
              <button onClick={copy}
                className={`px-4 py-2 border rounded-lg text-sm font-semibold transition-colors ${copied ? 'bg-green-500 text-white border-green-500' : 'border-gray-300 text-gray-700 hover:bg-gray-50'}`}>
                {copied ? '✅ Copied!' : 'Copy All'}
              </button>
              <button onClick={download}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-semibold transition-colors">
                Download .txt
              </button>
            </div>
          </div>
          <textarea
            value={allText} readOnly rows={20}
            className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm bg-gray-50 text-gray-700 font-mono resize-none focus:outline-none"
          />
        </div>
      )}

      {status === 'done' && pages.length === 0 && (
        <p className="text-amber-600 text-sm text-center bg-amber-50 border border-amber-200 rounded-xl p-4">
          No text found. This PDF may contain only scanned images — OCR software is required to extract text from image-based PDFs.
        </p>
      )}
    </div>
  )
}

export default function PDFtoText() {
  return (
    <ToolPageShell
      slug="pdf-to-text"
      name="PDF to Text"
      description="Extract all text from a PDF file instantly — copy or download as a plain text file."
      icon="📝"
      steps={STEPS}
      faqs={FAQS}
      about={ABOUT}
      limitation={"Extracts only real text — scanned/image-based PDFs will return little or nothing (no OCR)."}
    >
      <PDFtoTextTool />
    </ToolPageShell>
  )
}
